preferences:
    general:
        audioLib: PTB
        units: deg

window:
    size: [1920, 1080]
    pos: [0, 0]
    color: [0, 0, 0]
    fullscr: True
    winType: pyglet
    waitBlanking: True

monitor:
    name: default
    width: 69.8  # in cm
    distance: 198  # in cm
    gamma: 1

operating system: linux

Task settings: 
    Response interval: [] # time in s you allow the participant to respond that still counts as correct response (only relevant for unambiguous stimuli)
    Stimulus names: ['', ''] # list of strings
    Blocks:  # e.g. 4 blocks would mean 2 rivalry and 2 unambiguous (alternated)
    Blocks practice: 2 # can be interrupted after every block - alternating ambiguous and unambiguous, ambiguous is always first 
    Previous percept duration: # list with frame values (still to be converted into screenticks!) or int in seconds
    Percept duration jitter: # in s, added to the previous percept duration (0.1 would be a random UNIFORM jitter between -0.1 and 0.1)
    Stimulus duration ambiguous: # duration in s
    Break duration: # duration in s
    Screenshot: # makes a screenshot when aborting experiment (only use without a subject!!)
    Test stimuli: # boolean
    Exit key: 'q'
    Break buttons: 'b'
    Monitor refreshrate: # in Hz
    Screentick conversion: # the value used to calculate how many screenticks there are per frame (check Readme for how we use the term 'frame')
    Test eyetracker: # boolean

# Those settings are experiemnt specific! Check the format of the stimulus filenames.
Stimulus settings: 
    Stimulus path: './stimuli/stimuli_186RGB/'
    Stimulus resolution: 800 # this will be used to load the correct stimulus! Pay attention to the filename format!
    Break stimulus name : 'fixation_screen'
    Dot size: 0.02 # same as stimulus resolution!
    Number frames: 190 # How many images of the globe do we have to complete one full rotation
    Number dots: 350 # how many dots are in the sphere (should be set in your filename)
    Sphere number ambiguous: 1 # create multiple spheres with the same parameters without overwriting the existing bmps
    Sphere number unambiguous: 5
    Black at back: 0.25 # the following paramter define color of dots and background 
    White at back: 0.75
    Black at front: 0
    White at front: 1
    Dot size min: 0.012 # size of the dots 
    Dot size max: 0.028

    # binocular rivalry specific
    Nr fading stimuli:
    Transition length: # in frames (note, still to be converted into screen ticks!)
    Stimulus size: 10 # stimulus size in degrees (INCLUDING FIXATION!)