preferences:
    general:
        audioLib: PTB
        units: deg

window:
    size: [1920, 1080]
    pos: [0, 0]
    color: [0, 0, 0]
    fullscr: True
    winType: pyglet
    waitBlanking: True

monitor:
    name: default
    width: 69.8  # in cm
    distance: 198  # in cm
    gamma: 1

operating system: linux

Task settings: 
    Response interval: [0.1, 1.5] # time in s you allow the participant to respond that still counts as correct response (only relevant for unambiguous stimuli)
    Stimulus names: ['House', 'Face'] # order does not matter. In the log file the reponse button indicates which one is upper or lower button
    Blocks: 4 # e.g. 4 blocks would mean 2 rivalry and 2 unambiguous (alternated)
    Blocks practice: 2 # can be interrupted after every block 
    Previous percept duration: 4 # list with frame values (still to be converted into screenticks!) or int in seconds
    Percept duration jitter: 0.1 # in s, added to the previous percept duration (0.1 would be a random UNIFORM jitter between -0.1 and 0.1)
    Stimulus duration ambiguous: 50 # 120 (2mins) duration in s
    Break duration: 2 # duration in s
    Screenshot: False # makes a screenshot when aborting experiment (only use without a subject!!)
    Test stimuli: False
    Exit key: 'q'
    Break buttons: 'b'
    Monitor refreshrate: 120 # or 120Hz
    Screentick conversion: 30 # The value used to calculate how many screenticks there are per frame (check Readme for how we use the term 'frame')
    Test eyetracker: False # boolean 
    
# Those settings are experiemnt specific! Check the format of the stimulus filenames.
Stimulus settings: 
    Stimulus path: './stimuli/BR_stimuli/'
    Stimulus size: 10 # stimulus size in degrees (INCLUDING FIXATION!)
    Nr fading stimuli: 255
    Transition length: 40 # in frames (note, still to be converted into screen ticks!)
    Break stimulus name : 'fixation_screen'